---
- name: Configure Elastic Load Balancer
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create Target Group
      ec2_target_group:
        name: my-target-group
        protocol: HTTP
        port: 80
        vpc_id: "your-vpc-id"
        state: present

    - name: Create Load Balancer
      ec2_elb_lb:
        name: my-load-balancer
        state: present
        subnets: ["subnet-12345678", "subnet-87654321"]
        security_groups: ["sg-12345678"]
        listeners:
          - protocol: HTTP
            load_balancer_port: 80
            instance_port: 80
        tags:
          Name: my-load-balancer

    - name: Register Instances with Target Group
      ec2_instance:
        state: present
        instance_ids: "i-12345678"
        target_groups: "my-target-group"

    - name: Configure Health Check
      elb_target_health:
        name: my-load-balancer
        state: present
        instance_ids: ["i-12345678"]
        target_group: my-target-group
        health_check:
          target: "HTTP:80/"
          interval: 30
          timeout: 5
          healthy_threshold: 3
          unhealthy_threshold: 2
